# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  psalm-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip
          tools: psalm

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Initialize Psalm Config (Only runs if psalm.xml is missing)
        run: |
          if [ ! -f psalm.xml ]; then
            psalm --init . 3
          fi

      - name: Run Psalm Scan
        run: psalm --output-format=github